
development:
  adapter: postgresql
  database: dev_venok
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: test_venok
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: production_venok
  pool: 5
  username: admin
  password: DD!!dd11

