
development:
  adapter: postgresql
  encoding: unicode
  database: dev_venok
  host: db
  username: postgres
  password:
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: production_venok
  pool: 5
  username: admin
  password: DD!!dd11
